from django.urls import path
from . import views

urlpatterns = [
    path('', views.index),
    path('login/', views.login),
    path('signup/', views.signup),
    path('register/', views.register),
    path('logout/', views.logout),
    path('dashboard/', views.dashboard),
    path('category/', views.categories),
    path('category/createCat/', views.createCat),
    path('category/<int:category_id>/viewCatItems', views.viewCatItems),
    path('shop/', views.shops),
    path('shop/createShop/', views.createShop),
    path('shop/<int:shop_id>/editShop/', views.viewShop),
    path('shop/<int:shop_id>/viewShopItems/', views.viewShopItems),
    path('shop/<int:shop_id>/updateShop/', views.updateShop),
    path('shop/<int:shop_id>/deleteShop/', views.deleteShop),
    path('product/', views.products),
    path('product/createProd/', views.createProd),
    path('product/<int:product_id>/editProd/', views.viewProd),
    path('product/<int:product_id>/viewItem/', views.viewItem),
    path('product/<int:product_id>/updateProd/', views.updateProd),
    path('product/<int:product_id>/deleteProd/', views.deleteProd),
    path('product/<int:product_id>/editNewProd/', views.viewNewProd),
    path('product/<int:product_id>/updateNewProd/', views.updateNewProd),
    path('product/<int:product_id>/assignShop/', views.assignShop),
    path('product/<int:product_id>/assignCat/', views.assignCat),
]