# Generated by Django 3.2.1 on 2021-05-12 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=45)),
                ('lastName', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('acctType', models.CharField(choices=[('O', 'Owner'), ('C', 'Customer')], max_length=1)),
                ('userCreatedAt', models.DateTimeField(auto_now_add=True)),
                ('userUpdatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopName', models.CharField(max_length=45)),
                ('shopDescription', models.TextField()),
                ('shopCreatedAt', models.DateTimeField(auto_now_add=True)),
                ('shopUpdatedAt', models.DateTimeField(auto_now=True)),
                ('shopOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store', to='marketApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=45)),
                ('itemDescription', models.TextField()),
                ('itemPrice', models.CharField(max_length=45)),
                ('itemImg', models.CharField(max_length=255)),
                ('itemCount', models.IntegerField()),
                ('itemShop', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='theShop', to='marketApp.shop')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catName', models.CharField(max_length=45)),
                ('catCreatedAt', models.DateTimeField(auto_now_add=True)),
                ('catUpdatedAt', models.DateTimeField(auto_now=True)),
                ('assignedCat', models.ManyToManyField(related_name='categories', to='marketApp.Product')),
            ],
        ),
    ]
