# Generated by Django 3.2 on 2021-05-14 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketApp', '0002_alter_user_acct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='itemShop',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='shopOwner',
        ),
        migrations.AddField(
            model_name='product',
            name='shop_id',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='marketApp.shop'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='marketApp.user'),
            preserve_default=False,
        ),
    ]
