# Generated by Django 3.2 on 2021-05-14 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketApp', '0003_auto_20210513_2325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='shop_id',
            new_name='shop',
        ),
    ]
