# Generated by Django 3.2 on 2021-05-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketApp', '0004_rename_shop_id_product_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='assignedCat',
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(related_name='products', to='marketApp.Category'),
        ),
    ]
